name: CI

on: [push, pull_request]

jobs:
  everything:
    name: Checkout, Build, and Lint # TODO: and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
    steps:
      - name: Check out a copy of the repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm install

      - name: Lint Ember addon JS
        run: npm run lint:js

      - name: Lint Ember addon HBS
        run: npm run lint:hbs

      # - name: Test Ember addon
      #   run: npm test
